/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Frigate Settings": {                            "en": "Frigate Settings",                                "de": "Fregatteneinstellungen",                          "ru": "Настройки фрегата",                               "pt": "Configurações da fragata",                        "nl": "Fregat instellingen",                             "fr": "Paramètres de la frégate",                        "it": "Impostazioni della fregata",                      "es": "Ajustes de fragata",                              "pl": "Ustawienia fregaty",                              "uk": "Налаштування фрегата",                            "zh-cn": "护卫舰设置"},
    "MQTT Object": {                                 "en": "MQTT Object",                                     "de": "MQTT-Objekt",                                     "ru": "Объект MQTT",                                     "pt": "Objeto MQTT",                                     "nl": "MQTT-object",                                     "fr": "Objet MQTT",                                      "it": "Oggetto MQTT",                                    "es": "Objeto MQTT",                                     "pl": "Obiekt MQTT",                                     "uk": "Об'єкт MQTT",                                     "zh-cn": "MQTT对象"},
    "Object:": {                                     "en": "Object",                                          "de": "Objekt",                                          "ru": "Объект",                                          "pt": "Objeto",                                          "nl": "Voorwerp",                                        "fr": "Objet",                                           "it": "Oggetto",                                         "es": "Objeto",                                          "pl": "Obiekt",                                          "uk": "Об'єкт",                                          "zh-cn": "目的"},
    "Frigate URL:": {                                "en": "Frigate URL",                                     "de": "Fregatten-URL",                                   "ru": "URL фрегата",                                     "pt": "URL da fragata",                                  "nl": "Fregat URL",                                      "fr": "URL de frégate",                                  "it": "URL fregata",                                     "es": "Fragata URL",                                     "pl": "Adres URL fregaty",                               "uk": "URL фрегата",                                     "zh-cn": "护卫舰网址"},
    "Select": {                                      "en": "Select",                                          "de": "Wählen",                                          "ru": "Выбирать",                                        "pt": "Selecione",                                       "nl": "Selecteer",                                       "fr": "Sélectionner",                                    "it": "Selezionare",                                     "es": "Seleccionar",                                     "pl": "Wybierać",                                        "uk": "Виберіть",                                        "zh-cn": "选择"},
    "Cancel": {                                      "en": "Cancel",                                          "de": "Stornieren",                                      "ru": "Отмена",                                          "pt": "Cancelar",                                        "nl": "Annuleren",                                       "fr": "Annuler",                                         "it": "Annulla",                                         "es": "Cancelar",                                        "pl": "Anulować",                                        "uk": "Скасувати",                                       "zh-cn": "取消"},
};