/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    'Frigate Settings': { 'en': 'Frigate Settings', 'de': 'Frigateeinstellungen', 'ru': 'Настройки фрегата', 'pt': 'Configurações da fragata', 'nl': 'Fregat instellingen', 'fr': 'Paramètres de la frégate', 'it': 'Impostazioni della fregata', 'es': 'Ajustes de fragata', 'pl': 'Ustawienia fregaty', 'uk': 'Налаштування фрегата', 'zh-cn': '护卫舰设置' },
    'Frigate URL:': { 'en': 'Frigate URL', 'de': 'Frigate-URL', 'ru': 'URL фрегата', 'pt': 'URL da fragata', 'nl': 'Fregat URL', 'fr': 'URL de frégate', 'it': 'URL fregata', 'es': 'Fragata URL', 'pl': 'Adres URL fregaty', 'uk': 'URL фрегата', 'zh-cn': '护卫舰网址' },
    'MQTT Object': {
        'en': 'MQTT Object', 'de': 'MQTT-Objekt', 'ru': 'Объект MQTT', 'pt': 'Objeto MQTT', 'nl': 'MQTT-object', 'fr': 'Objet MQTT', 'it': 'Oggetto MQTT', 'es': 'Objeto MQTT', 'pl': 'Obiekt MQTT', 'uk': 'Об'єкт MQTT',                                      'zh - cn': 'MQTT对象'},
};